---
title: "SLD Cleaning"
author: Sophia Pham
output: html_notebook
---

Download the full Smart Location Database CSV file here: https://catalog.data.gov/dataset/smart-location-database8
See the documentation, including feature descriptions, here: https://www.epa.gov/system/files/documents/2023-10/epa_sld_3.0_technicaldocumentationuserguide_may2021_0.pdf
```{r}
#load in the dataset
sld_orig <- read.csv("EPA_SmartLocationDatabase_V3_Jan_2021_Final.csv") # name not changed from download; make sure in the same folder as this notebook!
str(sld_orig) # vibe check the structure of the dataframe
```

```{r}
sld_NY_state <- sld_orig[sld_orig$STATEFP == 36, ] # 36 is NY State FIPS code, filter only NY state entries

# write.csv(sld_NY_state, "sld_NY_state.csv") # write only NY state entries to csv

#---below is the code for only filtering and naming counties in NY state (also it's not very efficient...)---
# sld_NY_state$countyName <- NA
# sld_NY_state$countyName <- ifelse(sld_NY_state$COUNTYFP == 47, "Brooklyn", sld_NY_state$countyName)
# sld_NY_state$countyName <- ifelse(sld_NY_state$COUNTYFP == 81, "Queens", sld_NY_state$countyName)
# sld_NY_state$countyName <- ifelse(sld_NY_state$COUNTYFP == 61, "Manhattan", sld_NY_state$countyName)
# sld_NY_state$countyName <- ifelse(sld_NY_state$COUNTYFP == 5, "Bronx", sld_NY_state$countyName)
# sld_NY_state$countyName <- ifelse(sld_NY_state$COUNTYFP == 85, "Staten Island", sld_NY_state$countyName)
# na.omit(sld_NY_state) # omit any counties that are not the 5 boroughs
#------------------------------------------------------------------------------------------------------------

#---NAMING COLUMNS-------------------------------------------------------------------------------------------
colnames(sld_NY_state)
sld_colnames <- c("Object ID",
                  
                  "CBG 12-digit FIPS (2010)", #------admin, 10--------------------
                  "CBG 12-digit FIPS (2018)",
                  "State FIPS",
                  "County FIPS",
                  "Tract FIPS",
                  "CBG FIPS code in which CBG resides",
                  "CSA Code", #combined statistical area
                  "CSA Name", 
                  "CBSA FIPS", #core-based statistical area
                  "CBSA Name",
                  
                  "CBSA Population", #--------------csba measures, 3----------------
                  "CBSA Total Employment",
                  "CSBA Worker Population",
                  
                  "Total Area (acres)", #each of these refer to the CBG indicated by the fips #---------------------------------area, 4-----------------------------
                  "Total Water Area (acres)",
                  "Total Land Area (acres)",
                  "Total Unprotected Land Area (acres)",
                  
                  "Total Population", #-------------demographics, 15-----------------
                  "Num. Housing Units",
                  "Num. Occupied Housing Units",
                  "Percent Working Age Population",
                  "Num. Zero-Car Households",
                  "Percent Zero-Car Households",
                  "Num. One-Car Households",
                  "Percent One-Car Households",
                  "Num. Multi-Car Households",
                  "Percent Multi-Car Households",
                  "Num. Workers",
                  "Num. Low Wage Workers (Home Loc.)", #<$1250 per month
                  "Num. Med. Wage Workers (Home Loc.)", #>$1250 and <$3333 per month
                  "Num. High Wage Workers (Home Loc.)", #>$3333 per month
                  "Percent Low Wage Workers (Home Loc.)",
                  
                  "Total Employment", #---------------employment, 18-----------------
                  "Num. Retail Jobs (5-tier class.)",
                  "Num. Office Jobs (5-tier class.)",
                  "Num. Industrial Jobs (5-tier class.)",
                  "Num. Service Jobs (5-tier class.)",
                  "Num. Entertainment Jobs (5-tier class.)",
                  "Num. Retail Jobs (8-tier class.)",
                  "Num. Office Jobs (8-tier class.)",
                  "Num. Industrial Jobs (8-tier class.)",
                  "Num. Service Jobs (8-tier class.)",
                  "Num. Entertainment Jobs (8-tier class.)",
                  "Num. Education Jobs (8-tier class.)",
                  "Num. Healthcare Jobs (8-tier class.)",
                  "Num. Public Admin. Jobs (8-tier class.)",
                  "Num. Low Wage Workers (Work Loc.)", #<$1250 per month
                  "Num. Med. Wage Workers (Work Loc.)", #>$1250 and <$3333 per month
                  "Num. High Wage Workers (Work Loc.)", #>$3333 per month
                  "Percent Low Wage Workers (Work Loc.)", 
                  
                  "Gross Residential Density (HU/acre)", #housing units (HU) #-----------density, 18-----------
                  "Gross Population Density (people/acre)",
                  "Gross Employment Density(jobs/acre)",
                  "Gross Retail (5-tier) Employment Density",
                  "Gross Office (5-tier) Employment Density",
                  "Gross Industrial (5-tier) Employment Density",
                  "Gross Service (5-tier) Employment Density",
                  "Gross Entertainment (5-tier) Employment Density",
                  "Gross Retail (8-tier) Employment Density",
                  "Gross Office (8-tier) Employment Density",
                  "Gross Industrial (8-tier) Employment Density",
                  "Gross Service (8-tier) Employment Density",
                  "Gross Entertainment (8-tier) Employment Density",
                  "Gross Education (8-tier) Employment Density",
                  "Gross Healthcare (8-tier) Employment Density",
                  "Gross Retail (8-tier) Employment Density",
                  "Gross Activity Density (employment+HUs)",
                  "Flag - Density based on total CBG land acreage",
                  
                  "Jobs per Household", #---------------diversity, 13----------------
                  "5-tier Employment Entropy (out of observed employment types)",
                  "5-tier Employment Entropy (out of 5 tiers)",
                  "8-tier Employment Entropy (out of observed employment types)",
                  "8-tier Employment Entropy (out of 8 tiers)",
                  "Employment and Household Entropy",
                  "Employment and Household Entropy (based on trips of 5 tiers)",
                  "Employment and Household Entropy (based on trips from 4 of 5 tiers)",
                  "Trip Attractions and Trip Attractions Equilibrium Index", # closer to 1 = more balanced trip making
                  "Job/Pop. Regional Diversity",
                  "Household Workers per Job, regional",
                  "Household Workers per Job, CBG",
                  "Household Workers per Job Equilibrium Index", #closer to 1 = more balanced resident workers & jobs in CBG
                  
                  "Total Road Network Density", #-------------design, 10-------------
                  "Network Density, Facility Miles of Auto-Oriented Links per Sq. Mile",
                  "Network Density, Facility Miles of Multi-modal Links per Sq. Mile",
                  "Network Density, Facility Miles of Pedestrian-Oriented Links per Sq. Mile",
                  "Street Intersection Density", # weighted, no auto-oriented intersections
                  "Intersection Density, Auto-Oriented Intersections per Sq. Mile",
                  "Intersection Density, Multi-modal Intersections (Three Legs) per Sq. Mile",
                  "Intersection Density, Mutli-modal Intersections (Four or More Legs) per Sq. Mile",
                  "Intersection Density, Pedestrian-Oriented Intersections (Three Legs) per Sq. Mile",
                  "Intersection Density, Pedestrian-Oriented Intersections (Four or More Legs) per Sq. Mile",
                  
                  "Distance from Pop. Weighted Centroid to Nearest Transit Stop (meters)", #---------transit access, 6-------------
                  "Proportion of CBG Employment Within 1/4 Mile of Fixed-Guideway Transit Stop",
                  "Proportion of CBG Employment Within 1/2 Mile of Fixed-Guideway Transit Stop",
                  "Aggregate Frequency of Transit Service Withing 1/4 Mile of CBG Boundary During Peak Evening Period (per hour)",
                  "Aggregate Frequency of Transit Service per Sq. Mile",
                  "Aggregate Frequency of Transit Service per Capita",
                  
                  "Jobs Within 45 Minutes Auto Travel Time", #----destination accessibility, 12----
                  "Working Age Population Within 45 Minutes Auto Travel Time",
                  "Jobs within 45 Minutes Transit Commute", 
                  "Working Age Population Within 45 Minutes Transit Commute",
                  "Proportional Accessibility to Regional Desinations by Auto - Employment Accessibility",
                  "Regional Centrality Index, Auto - D5cr",
                  "Proportional Accessibility to Regional Desinations by Auto - Working Age Population Accessibility",
                  "Regional Centrality Index, Auto - D5ce",
                  "Proportional Accessibility to Regional Desinations by Transit - Employment Accessibility",
                  "Regional Centrality Index, Transit - D5dr",
                  "Proportional Accessibility to Regional Desinations by Transit - Working Age Population Accessibility",
                  "Regional Centrality Index, Transit - D4de",
                  
                  "Walkability Quartile Ranked Order of D2a", #------walkability index, 5-----
                  "Walkability Quartile Ranked Order of D2b",
                  "Walkability Quartile Ranked Order of D3b",
                  "Walkability Quartile Ranked Order of D4a",
                  "Walkability Index",
                  
                  "Shape Length", #------------shape-----------
                  "Shape Area")

length(sld_colnames) # check that vector length matches num cols
colnames(sld_NY_state) <- sld_colnames # assign new col names
```

Download the zipped FIPS_data folder and extract it (as a folder) to the directory that this notebook is in.
```{r}
county_FIPS <- read.csv("./FIPS_data/County FIPS Codes.csv")
county_FIPS_NY <- county_FIPS[county_FIPS$State.FIPS.code == 36, ] #only include the counties in NY state

# process the county fips so they match the format of the SLD (36001 --> 1)
for (i in 1:length(county_FIPS_NY$County.Name)){
  county_FIPS_NY[i,"County.FIPS.code"] = county_FIPS_NY[i,"County.FIPS.code"] - 36000
}
```

```{r}
zip_FIPS <- read.csv("./FIPS_data/ZIP codes to FIPS codes.csv")
```
